// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {apps} from '../models';
import {backup} from '../models';
import {main} from '../models';

export function CheckAppInstalled(arg1:string):Promise<boolean>;

export function CountAutoBackups():Promise<number>;

export function CreateBackup(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function DeleteApp(arg1:string):Promise<void>;

export function DeleteNote(arg1:string):Promise<void>;

export function DeleteSession(arg1:string,arg2:string):Promise<void>;

export function FormatSize(arg1:number):Promise<string>;

export function GenerateNewID(arg1:string):Promise<number>;

export function GetActiveApps():Promise<Array<apps.AppConfig>>;

export function GetActiveSession(arg1:string):Promise<string>;

export function GetAllSessions(arg1:boolean):Promise<Array<backup.Session>>;

export function GetApp(arg1:string):Promise<apps.AppConfig>;

export function GetAppDataPath(arg1:string):Promise<string>;

export function GetApps():Promise<Array<apps.AppConfig>>;

export function GetCurrentUser():Promise<string>;

export function GetNote(arg1:string):Promise<main.Note>;

export function GetNotes():Promise<Array<main.Note>>;

export function GetPlatformInfo():Promise<Record<string, string>>;

export function GetSessions(arg1:string,arg2:boolean):Promise<Array<backup.Session>>;

export function IsAppRunning(arg1:string):Promise<boolean>;

export function KillApp(arg1:string):Promise<void>;

export function LaunchApp(arg1:string):Promise<void>;

export function OpenAppFolder(arg1:string):Promise<void>;

export function OpenBackupFolder():Promise<void>;

export function OpenConfigFolder():Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function OpenSessionFolder(arg1:string,arg2:string):Promise<void>;

export function ReloadApps():Promise<void>;

export function RenameSession(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ResetApp(arg1:string,arg2:boolean,arg3:boolean):Promise<void>;

export function RestoreBackup(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SaveApp(arg1:apps.AppConfig):Promise<void>;

export function SaveNote(arg1:main.Note):Promise<void>;

export function SelectExeFromLocalPrograms(arg1:string):Promise<string>;

export function SelectFile(arg1:string,arg2:Array<string>):Promise<string>;

export function SelectFolder(arg1:string):Promise<string>;

export function SelectFolderFromHome(arg1:string):Promise<string>;

export function SelectFolderFromLocalPrograms(arg1:string):Promise<string>;

export function SelectFolderFromRoaming(arg1:string):Promise<string>;

export function SetActiveSession(arg1:string,arg2:string):Promise<void>;

export function ToggleApp(arg1:string):Promise<void>;
