// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAppInstalled(arg1) {
  return window['go']['main']['App']['CheckAppInstalled'](arg1);
}

export function CountAutoBackups() {
  return window['go']['main']['App']['CountAutoBackups']();
}

export function CreateBackup(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateBackup'](arg1, arg2, arg3);
}

export function DeleteApp(arg1) {
  return window['go']['main']['App']['DeleteApp'](arg1);
}

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function DeleteSession(arg1, arg2) {
  return window['go']['main']['App']['DeleteSession'](arg1, arg2);
}

export function FormatSize(arg1) {
  return window['go']['main']['App']['FormatSize'](arg1);
}

export function GenerateNewID(arg1) {
  return window['go']['main']['App']['GenerateNewID'](arg1);
}

export function GetActiveApps() {
  return window['go']['main']['App']['GetActiveApps']();
}

export function GetActiveSession(arg1) {
  return window['go']['main']['App']['GetActiveSession'](arg1);
}

export function GetAllSessions(arg1) {
  return window['go']['main']['App']['GetAllSessions'](arg1);
}

export function GetApp(arg1) {
  return window['go']['main']['App']['GetApp'](arg1);
}

export function GetAppDataPath(arg1) {
  return window['go']['main']['App']['GetAppDataPath'](arg1);
}

export function GetApps() {
  return window['go']['main']['App']['GetApps']();
}

export function GetCurrentUser() {
  return window['go']['main']['App']['GetCurrentUser']();
}

export function GetNote(arg1) {
  return window['go']['main']['App']['GetNote'](arg1);
}

export function GetNotes() {
  return window['go']['main']['App']['GetNotes']();
}

export function GetPlatformInfo() {
  return window['go']['main']['App']['GetPlatformInfo']();
}

export function GetSessions(arg1, arg2) {
  return window['go']['main']['App']['GetSessions'](arg1, arg2);
}

export function IsAppRunning(arg1) {
  return window['go']['main']['App']['IsAppRunning'](arg1);
}

export function KillApp(arg1) {
  return window['go']['main']['App']['KillApp'](arg1);
}

export function LaunchApp(arg1) {
  return window['go']['main']['App']['LaunchApp'](arg1);
}

export function OpenAppFolder(arg1) {
  return window['go']['main']['App']['OpenAppFolder'](arg1);
}

export function OpenBackupFolder() {
  return window['go']['main']['App']['OpenBackupFolder']();
}

export function OpenConfigFolder() {
  return window['go']['main']['App']['OpenConfigFolder']();
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function OpenSessionFolder(arg1, arg2) {
  return window['go']['main']['App']['OpenSessionFolder'](arg1, arg2);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function ReloadApps() {
  return window['go']['main']['App']['ReloadApps']();
}

export function RenameSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameSession'](arg1, arg2, arg3);
}

export function ResetApp(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResetApp'](arg1, arg2, arg3);
}

export function RestoreAccountOnly(arg1, arg2) {
  return window['go']['main']['App']['RestoreAccountOnly'](arg1, arg2);
}

export function RestoreBackup(arg1, arg2, arg3) {
  return window['go']['main']['App']['RestoreBackup'](arg1, arg2, arg3);
}

export function SaveApp(arg1) {
  return window['go']['main']['App']['SaveApp'](arg1);
}

export function SaveNote(arg1) {
  return window['go']['main']['App']['SaveNote'](arg1);
}

export function SelectExeFromLocalPrograms(arg1) {
  return window['go']['main']['App']['SelectExeFromLocalPrograms'](arg1);
}

export function SelectFile(arg1, arg2) {
  return window['go']['main']['App']['SelectFile'](arg1, arg2);
}

export function SelectFolder(arg1) {
  return window['go']['main']['App']['SelectFolder'](arg1);
}

export function SelectFolderFromHome(arg1) {
  return window['go']['main']['App']['SelectFolderFromHome'](arg1);
}

export function SelectFolderFromLocalPrograms(arg1) {
  return window['go']['main']['App']['SelectFolderFromLocalPrograms'](arg1);
}

export function SelectFolderFromRoaming(arg1) {
  return window['go']['main']['App']['SelectFolderFromRoaming'](arg1);
}

export function SetActiveSession(arg1, arg2) {
  return window['go']['main']['App']['SetActiveSession'](arg1, arg2);
}

export function ToggleApp(arg1) {
  return window['go']['main']['App']['ToggleApp'](arg1);
}
